sudo: false
language: node_js
node_js:
  - "0.10"
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install
  - bower install
script: grunt build s3
branches:
  only:
    - master
