sudo: false
language: node_js
node_js:
  - "0.10"
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install
  - bower install
script: node_modules/.bin/grunt build
after_success:
  - ls -la dist
  - node_modules/.bin/grunt s3
